/*'SQLeiro das galaxies' guide, a quick and 'practical' introduction to SQL*/
/*AULA 19*/


/* -- --------------------------------------------------------------------------------------- -- */
/* PERACOES EM LINHA */
SELECT * FROM VENDEDORES;
SELECT NOME,JANEIRO,FEVEREIRO,MARCO,(JANEIRO+FEVEREIRO+MARCO) AS "TOTAL",
    TRUNCATE((JANEIRO+FEVEREIRO+MARCO)/3,2) AS "MEDIA"
	    FROM VENDEDORES;

/* APLICANDO UM %*/
SELECT NOME,JANEIRO,FEVEREIRO,MARCO,(JANEIRO+FEVEREIRO+MARCO) AS "TOTAL",
	(JANEIRO+FEVEREIRO+MARCO) * .25 AS "DESCONTO",
	TRUNCATE((JANEIRO+FEVEREIRO+MARCO)/3,2) AS "MEDIA"
	    FROM VENDEDORES;

