/*'SQLeiro das galaxies' guide, a quick and 'practical' introduction to SQL*/
/*AULA 22*/


/* -- --------------------------------------------------------------------------------------- -- */
/* TRIGGERS */
/* ESTRUTURA DE UMA TRIGGER */

/* 
CREATE TRIGGER NOME
BEFORE/AFTER INSERT/DELETE/UPDATE ON TABELA
FOR EACH NOW (PARA CADA LINHA)
BEGIN -> INICIO
	QUALQUER COMANDO SQL
END -> FIM
$
*/

CREATE DATABASE TESTE_TRIGGERS;
USE  TESTE_TRIGGERS;

CREATE TABLE USUARIO(
	IDUSUARIO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	LOGIN VARCHAR(30),
	SENHA VARCHAR(30)
);

CREATE TABLE BKP_USUARIO(
	IDBACKUP INT PRIMARY KEY AUTO_INCREMENT,
	IDUSUARIO INT,
	NOME VARCHAR(30),
	LOGIN VARCHAR(30)
);

/* CRIANDO A TRIGGER */
DELIMITER $
STATUS

CREATE TRIGGER BACKUP_USER
BEFORE DELETE ON USUARIO -- ANTES DE OCORRER UM DELETE NA TABELA USUARIO
FOR EACH ROW -- PARA CADA LINHA
BEGIN
	INSERT INTO BKP_USUARIO VALUES 
		(NULL,OLD.IDUSUARIO,OLD.NOME,OLD.LOGIN);
END
$

DELIMITER ;

INSERT INTO USUARIO VALUES (NULL,"LUCAS","TARMIEL","TARMIL123");
SELECT * FROM USUARIO;
DELETE FROM USUARIO WHERE IDUSUARIO = 1;
SELECT * FROM BKP_USUARIO;

/* VISUALIZAR TRIGGERS */
SHOW TRIGGERS FROM NOME_DO_BANCO;

