/*'SQLeiro das galaxies' guide, a quick and 'practical' introduction to SQL*/
/*AULA 01*/


/* MODELAGEM BASICA */
-- TABELA CLIENTE
    -- A TABELA É CONSTITUIDA PELO NOME DO ATRIBUTO E SEU TIPO / TAMANHO(SE NECESSÁRIO)
	NOME . CARACTER(30)
	CPF	. NUMERICO(11) 
	EMAIL . CARACTER(30)
	TELEFONE . CARACTER(30)
	SEXO . CARACTER(1)
	ENDERECO . CARACTER(100)


/* PROCESSOS DE MODELAGEM */
-- ADM DE DADOS
	MODELAGEM CONCEITUAL - RASCUNHO
	MODELAGEM LOGICA - PROGRAMAS COMO DRAW.IO
-- AD - DBA
	MODELAGEM FISICA - SCRIPT DO BANCO


/* PARA UM "MELHOR PROVEITO" UTILIZE O BANCO VIA TERMINAL*/
/* CRIANDO O BANCO DE DADOS */
CREATE DATABASE CURSO;

-- CONECTANDO
USE CURSO;

-- CRIANDO A TABELA CLIENTE
CREATE TABLE CLIENTE(
	NOME VARCHAR(30),
	SEXO CHAR(1), -- M ou F
	EMAIL VARCHAR(30),
	CPF INT(11),
	TELEFONE VARCHAR(30),
	ENDERECO VARCHAR(100)
);

-- VERIFICANDO AS TABELAS - APENAS MYSQL
SHOW TABLES;

-- DESCREVENDO TABELAS
DESC CLIENTE;


/* -- ---------------------------------------------------------------------------------------- -- */


-- FORMA 01 - INSERT - EXCLUINDO AS COLUNAS
INSERT INTO CLIENTE VALUES('JOAO','M','JOAO@GMAIL.COM',988638273,'22923110','MAIA LACERDA - ESTACIO - RIO DE JANEIRO -RJ');
INSERT INTO CLIENTE VALUES('CELIA','F','CELIA@GMAIL.COM',541521456,'25078869','RIACHUELO - CENTRO - RIO DE JANEIRO -RJ');
INSERT INTO CLIENTE VALUES('JORGE','M',NULL,885755896,'58748895','OSCAR CURY - BOM RETIRO - FSTOS DE MINAS - MG');

-- FORMA 02 - INCLUINDO AS COLUNAS
INSERT INTO CLIENTE(NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES('LILIAN','F','SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ','985691511',1234567891);

-- FORMA 03 - INSERT COMPACTO - SOMENTE MYSQL
INSERT INTO CLIENTE VALUES('ANA','F','ANA@GLOBO.COM',85959543,'548556985','PRES ANTONIO CARLOS - CENTRO - SÃO PAULO - SP'),
						('CARLA','F','CARLA@TERARI.COM.BR',774582058,'66587458','SAMUEL SILVA - CENTRO - BELO HORIZONTE - BH');
	
					
/* -- ---------------------------------------------------------------------------------------- -- */
/* O COMANDO SELECT */
SELECT NOW(); -- COMO O NOME JÁ DIZ, SELECIONE AGORA (DATA E HORA)
SELECT 'TARMIEL'; -- SELECIONA UM ATRIBUTO(COLUNA) E TUPLA(REGISTRO) CHAMADO TARMIEL, MESMO QUE NÃO EXISTA
SELECT 'BANCO DE DADOS';

-- ALIAS DE COLUNAS
SELECT 'TARMIEL' AS ALUNO; -- APELIDANDO ATRIBUTOS(COLUNAS)

SELECT NOME,SEXO,EMAIL FROM CLIENTE;
SELECT * FROM CLIENTE; -- * = TUDO

