/*'SQLeiro das galaxies' guide, a quick and 'practical' introduction to SQL*/
/*AULA 09*/


/* -- ---------------------------------------------------------------------------------------- -- */
/* INSERINDO REGISTROS */
INSERT INTO CLIENTE VALUES(NULL,'JOAO','M','JOAO@IG.COM','98547-6');
INSERT INTO CLIENTE VALUES(NULL,'CARLOS','M','CARLOS@TERA.COM','986664-7');
INSERT INTO CLIENTE VALUES(NULL,'ANA','F','ANA@GLOBO.COM','75658-5');
INSERT INTO CLIENTE VALUES(NULL,'JORGE','M','JORGE@IG.COM','88657-5');
INSERT INTO CLIENTE VALUES(NULL,'CLARA','M',NULL,'99754-7');
INSERT INTO CLIENTE VALUES(NULL,'CELIA','F','JOAO@TERRA.COM','77558-5');

SELECT * FROM CLIENTE;

-- INSERINDO UM REGISTRO ERRADO
INSERT INTO CLIENTE VALUES(NULL,'ANTONIO','M','JOAO@IG.COM');
-- CORRIGINDO
INSERT INTO CLIENTE VALUES(NULL,'ANTONIO','M',NULL,'78558-6');
INSERT INTO CLIENTE VALUES(NULL,'JOAO','M',NULL,'86695-6');

-- DESCREVER TABELA ENDERECO + ORDEM DOS INSERTS
DESC ENDERECO ;

INSERT INTO ENDERECO VALUES(NULL,'RUA A','ITAPERI','FORTALEZA','CE',1); 
    -- O ULTIMO VALOR(1) REFERENCIA O IDCLIENTE DA TABELA CLIENTE
    -- OU SEJA, ESSE ENDERECO PERTENCE AO CLIENTE DE ID = 1
INSERT INTO ENDERECO VALUES(NULL,'RUA B','CIDADE DOS FUNCIONARIOS','FORTALEZA','CE',2); -- CLIENTE DE IDCLIENTE = 2 MORA EM RUA B
INSERT INTO ENDERECO VALUES(NULL,'RUA C','MEIRELES','FORTALEZA','CE',3); -- CLIENTE DE IDCLIENTE = 3 MORA EM RUA C
INSERT INTO ENDERECO VALUES(NULL,'RUA D','CENTRO','EUCLIDES DA CUNHA','BH',7);
INSERT INTO ENDERECO VALUES(NULL,'RUA E','JARDIM','RIO DE JANEIRO','RJ',8);
INSERT INTO ENDERECO VALUES(NULL,'RUA F','SAO GONCALO','SAO PAULO','SP',5);
INSERT INTO ENDERECO VALUES(NULL,'RUA G','JARDIM','RIO DE JANEIRO','RJ',6);
INSERT INTO ENDERECO VALUES(NULL,'RUA H','CENTRO','BELEM','BE',4);

-- INSERINDO UM REGISTRO 'ERRADO'
-- LEMBRANDO, O CLIENTE SÓ PODE TER UM ENDEREÇO, E AQUI TENTAMOS ADICIONAR
-- OUTRO ENDEREÇO AO CLIENTE DE ID = 6
INSERT INTO ENDERECO VALUES(NULL,'RUA X','JARDIM','NITEROI','RJ',6);
SELECT * FROM ENDERECO e ;


-- DESCREVER TABELA TELEFONE - ORDEM DOS INSERTS
DESC TELEFONE;

INSERT INTO TELEFONE VALUES(NULL,'RES','3222222',1); 
    -- CLIENTE DE ID = 1 TEM TELEFONE RES
INSERT INTO TELEFONE VALUES(NULL,'CEL','3223234',2); 
    -- CLIENTE DE ID = 2 TEM TELEFONE CEL
INSERT INTO TELEFONE VALUES(NULL,'COM','6543422',3);
INSERT INTO TELEFONE VALUES(NULL,'CEL','542OO99',5);
INSERT INTO TELEFONE VALUES(NULL,'COM','3222222',7);
INSERT INTO TELEFONE VALUES(NULL,'RES','3222222',8);
INSERT INTO TELEFONE VALUES(NULL,'CEL','3222222',2); 
    -- CLIENTE DE ID = 2 (NOVAMENTE) TEM OUTRO TELEFONE CEL
INSERT INTO TELEFONE VALUES(NULL,'COM','3222222',3);
INSERT INTO TELEFONE VALUES(NULL,'CEL','3222222',3);

-- TESTE RÁPIDO, SELECIONANDO NOME,EMAIL,NUMERO,TIPO,ID_CLIENTE E ORDENANDO POR NOME
-- EXIBE OS CLIENTES,O EMAIL,NUMEROS,TIPO E ID
SELECT IDCLIENTE,NOME,EMAIL,NUMERO,TIPO
	FROM CLIENTE c
	INNER JOIN TELEFONE t
	ON IDCLIENTE = ID_CLIENTE
	ORDER BY NOME;
    -- 'AGRUPANDO/CONECTANDO' TABELAS UTILIZANDO INNER JOIN...
    -- ONDE IDCLIENTE DA TABELA CLIENTE = ID_CLIENTE DA TABELA TELEFONE


-- SELECIONANDO ...... AGRUPANDO E ORDENANDO + CONTANDO QUANTOS TELEFONES TEM CADA UM
-- "SEMPRE" QUE USAR COUNT,USE GROUP BY
SELECT IDCLIENTE,NOME,EMAIL,COUNT(IDCLIENTE) AS QTD_NUMEROS
	FROM CLIENTE c 
	INNER JOIN TELEFONE 
	ON IDCLIENTE = ID_CLIENTE 
	GROUP BY IDCLIENTE -- AGRUPANDO PELA COLUNA IDCLIENTE
	ORDER BY NOME; -- E ORDENE PELO NOME 

SELECT * FROM CLIENTE c ;
SELECT * FROM ENDERECO e ;
SELECT * FROM TELEFONE t ;

