/*'SQLeiro das galaxies' guide, a quick and 'practical' introduction to SQL*/
/*AULA 10*/


/* -- ---------------------------------------------------------------------------------------- -- */
/* A13 - SELEÇÃO, PROJEÇÃO E JUNÇÃO */
-- PROJEÇÃO - TUDO QUE QUEREMOS PROJETAR NA TELA
-- PROJETEI A COLUNA DATA , QUE NÃO EXISTE EM NENHUMA TABELA
SELECT NOW() AS DATA;
SELECT NOME,NOW() AS "DATA" FROM CLIENTE; -- PROJEÇÃO


-- SELEÇÃO - TEORIA DOS CONJUNTOS
SELECT NOME, SEXO
	FROM CLIENTE c ; -- SELEÇÃO
 
SELECT NOME, SEXO
	FROM CLIENTE c 
	WHERE SEXO = 'M'; -- SELEÇÃO 

UPDATE CLIENTE 
	SET SEXO = 'F'
	WHERE IDCLIENTE = 5;


-- JUNÇÃO
-- SELECIONE NOME,SEXO,BAIRRO E CIDADE ONDE A CHAVE PRIMARIA DE CLIENTE SEJA = CHAVE ESTRANGEIRA DE  ENDEREÇO
-- NÃO UTILIZAR WHERE PARA JUNÇÃO
SELECT NOME,SEXO,BAIRRO, CIDADE, NOW() AS DATA
	FROM CLIENTE , ENDERECO
	WHERE IDCLIENTE = ID_CLIENTE; -- SELEÇÃO

SELECT NOME,SEXO,BAIRRO, CIDADE, NOW() AS DATA
	FROM CLIENTE , ENDERECO
	WHERE IDCLIENTE = ID_CLIENTE
	AND BAIRRO = 'CENTRO';

-- JOIN
SELECT NOME,SEXO,BAIRRO,CIDADE -- PROJEÇÃO
	FROM CLIENTE
	INNER JOIN ENDERECO -- JUNÇÃO 
	ON IDCLIENTE = ID_CLIENTE; -- SELEÇÃO

-- EVITAR ERRO DE CLAUSE AMBIGUOUS , ID_CLIENTE
SELECT CLIENTE.NOME,CLIENTE.SEXO,ENDERECO.BAIRRO,ENDERECO.CIDADE,TELEFONE.TIPO,TELEFONE.NUMERO
	FROM CLIENTE
	INNER JOIN ENDERECO
	ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE
	INNER JOIN TELEFONE
	ON CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE;

-- ATRIBUINDO APELIDOS
SELECT NOME,SEXO,BAIRRO,CIDADE,TIPO,NUMERO
	FROM CLIENTE c
	INNER JOIN ENDERECO e
	ON c.IDCLIENTE = e.ID_CLIENTE
	INNER JOIN TELEFONE t
	ON c.IDCLIENTE = t.ID_CLIENTE;

SELECT NOME,SEXO,EMAIL,BAIRRO,CIDADE,TIPO,NUMERO
	FROM CLIENTE c
	INNER JOIN ENDERECO e
	ON c.IDCLIENTE = e.ID_CLIENTE
	INNER JOIN TELEFONE t
	ON c.IDCLIENTE = t.ID_CLIENTE
	WHERE SEXO = 'M';

