/*'SQLeiro das galaxies' guide, a quick and 'practical' introduction to SQL*/
/*AULA 26*/


/* -- --------------------------------------------------------------------------------------- -- */
/* CURSORS */
CREATE DATABASE CURSORES;
USE CURSORES;

CREATE TABLE VENDEDORES(
	IDVENDEDOR INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(50),
	JAN INT,
	FEV INT,
	MARC INT
);

INSERT INTO VENDEDORES VALUES (NULL,'LUCAS',1400,2300,4400);
INSERT INTO VENDEDORES VALUES (NULL,'MARIA',2600,3000,1400);
INSERT INTO VENDEDORES VALUES (NULL,'CHESMA',6400,2300,6400);
INSERT INTO VENDEDORES VALUES (NULL,'JEFERSON',3400,12300,1400);

SELECT * FROM VENDEDORES;

SELECT NOME, (JAN+FEV+MARC) AS TOTAL FROM VENDEDORES;
SELECT NOME, (JAN+FEV+MARC) AS TOTAL, TRUNCATE((JAN+FEV+MARC)/3,2) AS MEDIA FROM VENDEDORES;

CREATE TABLE VEND_TOTAL (
	NOME VARCHAR(50),
	JAN INT,
	FEV INT,
	MARC INT,
	TOTAL INT,
	MEDIA INT
);

DELIMITER $

CREATE PROCEDURE INSERE_DADOS()
BEGIN
	DECLARE FIM INT DEFAULT 0;
	DECLARE VAR1, VAR2, VAR3,VTOTAL,VMEDIA INT; --TODOS DO TIPO INT
	DECLARE VNOME VARCHAR(50);

	DECLARE REG CURSOR FOR( -- É COMO UM FOR EACH
        -- JOGANDO OS VALORES DENTRO DE REG
		SELECT NOME, JAN, FEV, MARC FROM VENDEDORES	
	);

	DECLARE CONTINUE HANDLER FOR NOT FOUND SET FIM = 1;

	OPEN REG; -- JOGAR OS VALORES NA MEMORIA

	REPEAT
		FETCH REG INTO VNOME, VAR1, VAR2, VAR3; -- JOGANDO DENTRO DAS VARIÁVEIS
		IF NOT FIM THEN
			SET VTOTAL = VAR1+VAR2+VAR3;
			SET VMEDIA = VTOTAL/3;

			INSERT INTO VEND_TOTAL VALUES(VNOME,VAR1,VAR2,VAR3,VTOTAL,VMEDIA);  
		END IF;
	UNTIL FIM END REPEAT;
	CLOSE REG;
END
$

DELIMITER ;

SELECT * FROM VEND_TOTAL;
CALL INSERE_DADOS();
SELECT * FROM VEND_TOTAL;

-- ESTUDE A FUNDO CURSORS
