/*'SQLeiro das galaxies' guide, a quick and 'practical' introduction to SQL*/
/*AULA 21*/


/* -- --------------------------------------------------------------------------------------- -- */
/* ORGANIZAÇAO DE CHAVES , CONSTRAINT(REGRA)*/
CREATE DATABASE TESTE_TIMES;

CREATE TABLE JOGADOR(
	IDJOGADOR INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30)
);

CREATE TABLE TIMES(
	IDTIME INT PRIMARY KEY AUTO_INCREMENT,
	NOMETIME VARCHAR(30),
	ID_JOGADOR INT,
	FOREIGN KEY(ID_JOGADOR) REFERENCES JOGADOR(IDJOGADOR)
        -- MANEIRA "ERRADA"
);

INSERT INTO JOGADOR VALUES(NULL,'GUERREIRO');
INSERT INTO TIMES VALUES(NULL,'FLAMENGO',1);

SHOW CREATE TABLE JOGADOR;
SHOW CREATE TABLE TIMES;

-- DICA: PRIMEIRO CRIAR AS TABELAS E DEPOIS AS CHAVES(FK) POR FORA


/* -- --------------------------------------------------------------------------------------- -- */
/* ORGANIZANDO CHAVES E ACOES DE CONSTRAINTS */
CREATE TABLE CLIENTE(
	IDCLIENTE INT,
	NOME VARCHAR(30)
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT,
	TIPO CHAR(3) NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	ID_CLIENTE INT
);

-- UTILIZANDO DE CONSTRAINT FACILITA A IDENTIFICAÇÃO NA HORA DE DESCREVER A TABELA
-- E SUAS CHAVES
ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE -- 'APELIDO'
PRIMARY KEY(IDCLIENTE);

ALTER TABLE TELEFONE ADD CONSTRAINT FK_CLIENTE_TELEFONE
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE);
-- FK - CLIENTE - TELEFONE = FOREIGN KEY - REFERENCIA A TABELA CLIENTE - VEM DA TABELA TELEFONE

SHOW CREATE TABLE TELEFONE;

/* DICIONARIO DE DADOS */
SHOW DATABASES;
USE information_schema;
SHOW TABLES;
DESC TABLE_CONSTRAINTS;

SELECT CONSTRAINT_SCHEMA AS "BANCO", 
		TABLE_NAME AS "TABELA",
		CONSTRAINT_NAME AS "NOME DA REGRA",
		CONSTRAINT_TYPE AS "TIPO"
    	FROM TABLE_CONSTRAINTS
    	WHERE CONSTRAINT_SCHEMA = "TESTE_TIMES";
    
/* APAGANDO CONSTRAINTS */
STATUS;
USE TESTE_TIMES;
    
ALTER TABLE TELEFONE
DROP FOREIGN KEY FK_CLIENTE_TELEFONE;

-- CONFIRA NOVAMENTE EM INFORMATION_SCHEMA
-- E ADICIONE NOVAMENTE A CONSTRAINT