/*'SQLeiro das galaxies' guide, a quick and 'practical' introduction to SQL*/
/*AULA 20*/


/* -- --------------------------------------------------------------------------------------- -- */
/* ALTERANDO TABELAS */
CREATE TABLE TABELA(
	COLUNA1 VARCHAR(30),
	COLUNA2 VARCHAR(30),
	COLUNA3 VARCHAR(30)
);

-- ADICIONANDO UMA PK
ALTER TABLE TABELA
	ADD PRIMARY KEY(COLUNA1);
DESC TABELA; -- DESCREVA

-- ADICIONANDO COLUNA SEM POSICAO. ULTIMA POSICAO
ALTER TABLE TABELA
	ADD COLUNA VARCHAR(30);

-- ADICIONANDO UMA COLUNA COM POSICAO
ALTER TABLE TABELA
	ADD COLUMN COLUNA4 VARCHAR(30) NOT NULL UNIQUE
	AFTER COLUNA3;
	
-- MODIFICANDO O TIPO DE UM CAMPO
ALTER TABLE TABELA MODIFY COLUNA2 DATE NOT NULL;

-- RENOMEANDO O NOME DA TABELA
ALTER TABLE TABELA
	RENAME PESSOA;

CREATE TABLE TIME(
	IDTIME INT PRIMARY KEY AUTO_INCREMENT,
	TIME VARCHAR(30),
	ID_PESSOA VARCHAR(30)
);
DESC TIME;

-- FOREIGN KEY
ALTER TABLE TIME
	ADD FOREIGN KEY(ID_PESSOA)
	REFERENCES PESSOA (COLUNA1);

-- DESCRICAO DETALHADA
SHOW CREATE TABLE TIME;

