/*'SQLeiro das galaxies' guide, a quick and 'practical' introduction to SQL*/
/*AULA 25*/


/* -- --------------------------------------------------------------------------------------- -- */
/* AUTO RELACIONAMENTO */
CREATE DATABASE CURSOS;
USE CURSOS;
CREATE TABLE CURSOS(
	IDCURSO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	VALOR FLOAT(10,2),
	HORAS FLOAT(10,2),
	IDREQ INT
);

ALTER TABLE CURSOS ADD CONSTRAINT FK_IDREQ
FOREIGN KEY (IDREQ) REFERENCES CURSOS(IDCURSO);

INSERT INTO CURSOS VALUES (NULL,'BD RELACIONAL',20,400.00, NULL);
INSERT INTO CURSOS VALUES (NULL,'PROG 2',50,800.00, 1);
INSERT INTO CURSOS VALUES (NULL,'LINGUAGEM ',10,400.00, NULL);
INSERT INTO CURSOS VALUES (NULL,'AUDITORIA DE SISTEMAS',30,400.00,1);
INSERT INTO CURSOS VALUES (NULL,'MATEMATICA COMPUTACIONAL',40,500.00, 3);

SELECT * FROM CURSOS;
SELECT NOME,VALOR,HORAS,IFNULL(IDREQ,"SEM REQUISITOS") REQUISITO FROM CURSOS;

SELECT 
C.NOME AS CURSO,
C.VALOR AS VALOR,
C.HORAS AS CARGA,
IFNULL(P.NOME,"---") AS PREREQ
FROM CURSOS C
LEFT JOIN CURSOS P
ON P.IDCURSO = C.IDREQ

