/*'SQLeiro das galaxies' guide, a quick and 'practical' introduction to SQL*/
/*AULA 12*/


/* IFNULL */
SELECT NOME,
	   IFNULL(EMAIL,'SEM EMAIL') AS EMAIL,
       -- EXIBA 'SEM EMAIL' PARA OS VALORES VAZIOS DO ATRIBUTO EMAIL
	   NUMERO
	FROM CLIENTE c 
	INNER JOIN TELEFONE t 
	ON c.IDCLIENTE = t.ID_CLIENTE 
	INNER JOIN ENDERECO e 
	ON c.IDCLIENTE = e.ID_CLIENTE 
	WHERE SEXO = 'F' AND TIPO = 'CEL' AND ESTADO = 'SP';

SELECT IDCLIENTE AS "CODIGO",NOME AS "CLIENTE",
	   IFNULL(EMAIL,'SEM EMAIL') AS "EMAIL"
	FROM CLIENTE c;

