/*'SQLeiro das galaxies' guide, a quick and 'practical' introduction to SQL*/
/*AULA 11*/


/* PARA UMA CAMPANHA DE MARKETING, O SETOR SOLICITOU UM RELATÓRIO 
 * COM O NOME, EMAIL E TELEFONE CELULAR DOS CLIENTES
 * QUE MORAM NO ESTADO  DO RIO DE JANEIRO
 * VOCÊ TERÁ QUE PASSAR A QUERY PARA GERAR O RELATÓRIO PARA O PROGRAMADOR*/

SELECT NOME,EMAIL,ESTADO,NUMERO,TIPO -- PROJEÇAO
	FROM CLIENTE c
	INNER JOIN TELEFONE t
	ON c.IDCLIENTE = t.ID_CLIENTE
	INNER JOIN ENDERECO e 
	ON c.IDCLIENTE  = e.ID_CLIENTE 
	WHERE TIPO = 'CEL' AND ESTADO = 'CE';
 
|NOME   |EMAIL            |ESTADO |NUMERO  |TIPO|
|-------|-----------------|-------|--------|----|
|CARLOS |CARLOS@TERA.COM  |CE     |3223234 |CEL |
|JORGE  |JORGE@IG.COM     |CE     |3222222 |CEL |
|CARLOS |CARLOS@TERA.COM  |CE     |3222222 |CEL |


/* PARA UMA CAMPANHA DE PRODUTOS DE BELEZA, O COMERCIAL SOLICITOU UM
 * RELATÓRIO COM O NOME, EMAIL E TELEFONE CELULAR
 * DAS MULHERES QUE MORAM NO ESTADO DE SÃO PAULO
 * VOCÊ TERÁ QUE PASSAR A QUERY PARA GERAR O RELATÓRIO PARA O PROGRAMADOR*/

SELECT NOME,EMAIL,NUMERO
	FROM CLIENTE c 
	INNER JOIN TELEFONE t 
	ON c.IDCLIENTE = t.ID_CLIENTE 
	INNER JOIN ENDERECO e 
	ON c.IDCLIENTE = e.ID_CLIENTE 
	WHERE SEXO = 'F' AND TIPO = 'CEL' AND ESTADO = 'SP';
