/*'SQLeiro das galaxies' guide, a quick and 'practical' introduction to SQL*/
/*AULA 24*/


/* -- --------------------------------------------------------------------------------------- -- */
/* TRIGGER DE AUDITORIA */

DROP DATABASE LOJA;
DROP DATABASE BACKUP;
DROP DATABASE BACKUP_DELETE;

CREATE DATABASE LOJA;
USE LOJA;
CREATE TABLE PRODUTO(
	IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	VALOR FLOAT(10,2)
);

INSERT INTO PRODUTO VALUES (NULL,'PAMONHA',4.00);
INSERT INTO PRODUTO VALUES (NULL,'CAJU',10.00);
INSERT INTO PRODUTO VALUES (NULL,'CD',2.00);
INSERT INTO PRODUTO VALUES (NULL,'DVD',4.00);


-- ....
SELECT NOW();
SELECT CURRENT_USER();

CREATE DATABASE BACKUP;
USE BACKUP;
CREATE TABLE BKP_PRODUTO(
	IDBKP INT PRIMARY KEY AUTO_INCREMENT,
	IDPRODUTO INT,
	NOME VARCHAR(30),
	VALOR_ORIGINAL FLOAT(10,2),
	VALOR_ALTERADO FLOAT(10,2),
	DATA DATETIME,
	USUARIO VARCHAR(30),
	EVENTO CHAR(1)
);

USE LOJA;
DELIMITER $

CREATE TRIGGER PRODUTO_UPDATE
AFTER UPDATE ON PRODUTO
FOR EACH ROW
BEGIN
	INSERT INTO BACKUP.BKP_PRODUTO VALUES(NULL,OLD.IDPRODUTO,OLD.NOME,OLD.VALOR,NEW.VALOR,NOW(),CURRENT_USER(),'U');	
END
$

DELIMITER ;
UPDATE PRODUTO SET VALOR = 110.00 
WHERE IDPRODUTO = 4;

SELECT * FROM BACKUP.BKP_PRODUTO;

